# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://api.shareabouts.org/api/v1/
dataset: urbansocial/urbansocial

# And the associated API key.
dataset_api_key: YOUR_KEY_HERE

# Settings for the app
app:
  # HTML Title
  title: Urban Social Spaces, Kendall Square
  # Header name
  name: Urban Social Spaces, Kendall Square
  # Meta description that will show up in Google search results
  meta_description: Urban Social Spaces is a study of where people connect in cities and how those interactions foster innovation.

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false
  options:
    center:
      lat:  42.36242
      lng: -71.085534
    zoom: 16
    minZoom: 13
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-streets/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Meeting:
    default: blue
    focused: red

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Add a Meeting!
  title: Tell us about it...
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: Meeting
    - prompt: Was this meeting scheduled or unscheduled?
      label: Scheduled?
      type: select
      options:
        - Scheduled
        - Unscheduled
      name: scheduled
    - prompt: Was this meeting professional or personal?
      label: Nature?
      type: select
      options:
        - Professional
        - Personal
      name: nature
    - prompt: Do you feel it led to meaningful ideas?
      label: Meaningful?
      type: select
      options:
        - 'Yes'
        - 'No'
      name: meaningful
    - prompt: Your Name
      label: 'Name:'
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
    - prompt: Short description of where you met
      lable: 'Location:'
      type: textarea
      name: place_desc
      optional: true
      attrs:
        - key: placeholder
          value: e.g. ground floor cafe, 5th floor conference room, the coffee shop on 3rd St

survey:
#   # Response display config
  show_responses: false

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: supported
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/about.html
    start_page: true
  - title: Kendall Innovation
    external: true
    url: http://kendallinnovation.blogspot.com
