# Settings for the app
app:
  # HTML Title
  title: WeHo Walk + Bike Better
  # Header name
  name: WeHo Walk + Bike Better
  # Meta description that will show up in Google search results
  meta_description: _(Share your insights and experiences to help make West Hollywood a more inviting city for pedestrians and bicyclists.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 34.089985
      lng: -118.361721
    zoom: 14
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  walking:
    default: walkingblue
    focused: walkingorange
    label: _(Walking)
  biking:
    default: bikinggreen
    focused: bikingorange
    label: _(Biking)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  walkingblue:
    iconUrl: /static/css/images/weho-walking-blue.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  walkinggreen:
    iconUrl: /static/css/images/weho-walking-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  walkingorange:
    iconUrl: /static/css/images/weho-walking-orange.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikingblue:
    iconUrl: /static/css/images/weho-biking-blue.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikinggreen:
    iconUrl: /static/css/images/weho-biking-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikingorange:
    iconUrl: /static/css/images/weho-biking-orange.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    # - prompt: _(Location Title)
    #   type: text
    #   name: name
    #   attrs:
    #     - key: placeholder
    #       value: _(Location Title)
    #     - key: size
    #       value: 30
    - prompt: _(Walking or Biking?)
      name: location_type
      type: select
      options:
        - label: _(Walking)
          value: walking
        - label: _(Biking)
          value: biking
    - prompt: _(Walk Better)
      name: walk_better
      type: select
      options:
        - label: _(This is a safe place to walk.)
          value: This is a safe place to walk.
        - label: _(This is an unsafe place to walk.)
          value: This is an unsafe place to walk.
        - label: _(This place is beautiful.)
          value: This place is beautiful.
        - label: _(This place is an eyesore.)
          value: This place is an eyesore.
        - label: _(Please put a crosswalk here.)
          value: Please put a crosswalk here.
        - label: _(Please widen the sidewalk here.)
          value: Please widen the sidewalk here.
        - label: _(This place needs better lighting.)
          value: This place needs better lighting.
        - label: _(This place needs better signage.)
          value: This place needs better signage.
        - label: _(An ADA facility is needed here.)
          value: An ADA facility is needed here.
    - prompt: _(Bike Better)
      name: bike_better
      type: select
      options:
        - label: _(This is a safe place to bike.)
          value: This is a safe place to bike.
        - label: _(This is an unsafe place to bike.)
          value: This is an unsafe place to bike.
        - label: _(Please put a bike lane here.)
          value: Please put a bike lane here.
        - label: _(This street isn't bike friendly.)
          value: This street isn't bike friendly.
        - label: _(Please add bike signage here.)
          value: Please add bike signage here.
        - label: _(This place needs bike parking.)
          value: This place needs bike parking.
        - label: _(Bikeshare should be here.)
          value: Bikeshare should be here.
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Email Address)
      type: text
      name: private-submitter_email_address
      optional: true
      attrs:
        - key: placeholder
          value: _(email@example.org)
        - key: size
          value: 30
    - prompt: _(ZIP Code)
      type: text
      name: private-submitter_zipcode
      optional: true
      attrs:
        - key: placeholder
          value: _(ZIP Code)
        - key: size
          value: 5


survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)
