# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://api.shareabouts.org/api/v1/
dataset: historiclouisville/historiclouisville

# And the associated API key.
dataset_api_key: YOUR_KEY_HERE

# Settings for the app
app:
  # HTML Title
  title: "Mapping Louisville's Historic Assets"
  # Header name
  name: "Mapping Louisville's Historic Assets"
  # Meta description that will show up in Google search results
  meta_description: Map of buildings, places, and heritage resources in Louisville, KY that the community values as historic and worth saving.

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false
  options:
    center:
      lat: 38.230629
      lng: -85.758963
    zoom: 13
    minZoom: 11
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-light/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Historic Location:
    default: blue
    focused: red

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Add a historic location!
  title: Tell us more...
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Name or address of the building or place
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Name or Address
        - key: size
          value: 30
    - prompt: ''
      name: location_type
      type: hidden
      attrs:
        - key: value
          value: Historic Location
    - prompt: Comment
      type: textarea
      name: comment
      optional: true
      attrs:
        - key: placeholder
          value: Any brief comment or personal memory about why this particular site is important to you
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/overview.html
    start_page: true

  - title: City Collaborative
    external: true
    url: http://citycollaborative.org

  - title: Download the Data!
    external: true
    url: /download/places.csv
