# Settings for the app
app:
  # HTML Title
  title: Where Should City Government Spend Our Tax Dollars?
  # Header name
  name: Where Should City Government Spend Our Tax Dollars?
  # Meta description that will show up in Google search results
  meta_description:  "Capital budget requests for the Brooklyn CB6 district"

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 40.68304631549296
      lng: -73.99699687957764
    zoom: 16
    minZoom: 15
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-uhk6289l/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Building/Facility Need:
    default: puck-blue
    focused: triangle-blue
  Roadway/Streetscape Need:
    default: puck-yellow
    focused: triangle-yellow
  Park/Open Space Need:
    default: puck-green
    focused: triangle-green

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  puck-green:
    iconUrl: /static/css/images/markers/dot-70d52c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  triangle-green:
    iconUrl: /static/css/images/markers/triangle-70d52c.png
    iconSize:
      width: 40
      height: 40
    iconAnchor:
      x: 20
      y: 20
  puck-blue:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  triangle-blue:
    iconUrl: /static/css/images/markers/triangle-2654d2.png
    iconSize:
      width: 40
      height: 40
    iconAnchor:
      x: 20
      y: 20
  puck-yellow:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  triangle-yellow:
    iconUrl: /static/css/images/markers/triangle-dbcf2c.png
    iconSize:
      width: 40
      height: 40
    iconAnchor:
      x: 20
      y: 20
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Identify a need
  title: Provide more information
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Add to map
  items:
    - prompt: Type of need
      type: select
      options:
        - label: _(Building/Facility Need)
          value: "Building/Facility Need"
        - label: _(Roadway/Streetscape Need)
          value: "Roadway/Streetscape Need"
        - label: _(Park/Open Space Need)
          value: "Park/Open Space Need"
      name: location_type
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Explain the need.
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: size
          value: 30
    - prompt: Your Email
      type: text
      name: private-email
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Give us a brief description of the problem or place, and the approximate time and day when you pass by here.
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: You must leave name to have your comment be visible to others.
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    name: overview
    start_page: true