# Settings for the app
app:
  # HTML Title
  title: Safer Sacramento
  # Header name
  name: Safer Sacramento
  # Meta description that will show up in Google search results
  meta_description:  "We want our sidewalks and streets to be safe, so that children can walk or bike to school and play areas. Please help us by identifying unsafe conditions on your route to school, and giving us suggestions about how to improve them."

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 38.5792709
      lng: -121.4898175
    zoom: 15
    minZoom: 11
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-jo9bww2s/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Speeding:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Speeding)
  Failure:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Failure to yield)
  Crosswalk:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Crosswalk needing repainting)
  SidewalkProblem:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Sidewalk problem)
  Other:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Other safety issue)
  Suggestion:
    default: bubbleexclamation
    focused: markerexclaimation
    label: _(Suggestion)
  NiceSpot:
    default: bubblethumb
    focused: markerthumb
    label: _(Nice spot!)
# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  bubblethumb:
    iconUrl: /static/css/images/bubble-thumbsup.png
    iconSize:
      width: 30
      height: 28
    iconAnchor:
      x: 25
      y: 26
  markerthumb:
    iconUrl: /static/css/images/marker-thumbsup.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bubbleexclamation:
    iconUrl: /static/css/images/bubble-exclamation.png
    iconSize:
      width: 30
      height: 28
    iconAnchor:
      x: 25
      y: 26
  markerexclaimation:
    iconUrl: /static/css/images/marker-exclamation.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: _(Identify a safety issue)
  title: _(Describe the problem)
  action_text: identified
  anonymous_name: Someone
  submit_button_label: _(Add to the map)
  items:
    - prompt: Issue
      type: select
      options:
        - label: _(Speeding)
          value: Speeding
        - label: _(Failure to yield)
          value: Failure
        - label: _(Crosswalk needs painting)
          value: Crosswalk
        - label: _(Sidewalk problem)
          value: SidewalkProblem
        - label: _(Other safety issue)
          value: Other
        - label: _(Suggestion)
          value: Suggestion
        - label: _(This spot is nice!)
          value: NiceSpot
      name: location_type
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: _(Give us a brief description of the problem or place, and the approximate time and day when you pass by here.)
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: _(Your name will be shown on the map alongside your comment.)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: _(Optionally, leave your email to stay informed.)
        - key: size
          value: 30      


survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Description
      type: textarea
      name: description
      optional: false
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: You must leave name to have your comment be visible to others.
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    name: overview
    start_page: false