# Settings for the app
app:
  # HTML Title
  title: CB3 Business Survey
  # Header name
  name: CB3 Business Survey
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false
  options:
    center:
      lat: 40.7267
      lng: -73.9808
    zoom: 16
    minZoom: 11
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  service:
    default: blue
    focused: red
    label: _(Service Business)
  vacant:
    default: blue
    focused: red
    label: _(Vacant Storefront)
  bar:
    default: blue
    focused: red
    label: _(Bar)
  retail:
    default: blue
    focused: red
    label: _(Retail Business)
  other:
    default: blue
    focused: red
    label: _(Other type of Business)
  restaurant:
    default: blue
    focused: red
    label: _(Restaurant)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: false
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(Landmark)
          value: landmark
        - label: _(Park)
          value: park
        - label: _(School)
          value: school
      name: location_type
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)

survey:
  submission_type: survey

  # Response config
  show_responses: true
  response_name: _(business survey)
  response_plural_name: _(business surveys)
  action_text: _(collected information on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Add a business)
  form_link_text: _(Add a business)
  submit_btn_text: _(Save Business Information)
  items:
    - prompt: _(Business Name)
      type: text
      name: business_name

    - prompt: _(Type of Business)
      name: business_type
      type: select
      options:
        - label: _(Vacant)
          value: vacant
        - label: _(Retail)
          value: retail
        - label: _(Bar)
          value: bar
        - label: _(Restaurant)
          value: restaurant
        - label: _(Service Business)
          value: service
        - label: _(Bank)
          value: bank
        - label: _(Grocery Store)
          value: grocery
        - label: _(Deli/Bodega)
          value: deli
        - label: _(Newspaper Stand)
          value: newspapers
        - label: _(Religious)
          value: religious
        - label: _(Cultural)
          value: cultural
        - label: _(Residential)
          value: residential
        - label: _(Other)
          value: other

    - prompt: _(What is sold?)
      name: retail_type
      condition:
        - field: business_type
          value: retail
      type: select
      options:
        - label: _(Clothing)
          value: clothing
        - label: _(Medical/Alternative Medicine)
          value: medical
        - label: _(Arts & Design)
          value: arts_design
        - label: _(Gifts)
          value: gifts
        - label: _(Jewelry)
          value: jewelry
        - label: _(Other)
          value: other

    - prompt: _(Other retail...)
      name: retail_type_other
      condition:
        - field: retail_type
          value: other
      type: text

    - prompt: _(Type of Food)
      name: food_type
      type: text
      condition:
        - field: business_type
          value: restaurant

    - prompt: _(Type of service offered)
      name: service_type
      condition:
        - field: business_type
          value: service
      type: text

    - prompt: _(Wheelchair accessible?)
      name: wheelchair_accessible
      type: switch

    - prompt: _(Hours of Operation)
      type: textarea
      name: hours

    - prompt: _(Contact Name)
      type: text
      name: contact_name

    - prompt: _(Contact Phone Number)
      type: tel
      name: phone_number
      attrs:
        - key: placeholder
          value: _((___) ___-____)

    - prompt: _(Contact Fax Number)
      type: tel
      name: fax_number
      attrs:
        - key: placeholder
          value: _((___) ___-____ )

    - prompt: _(Email Address)
      type: email
      name: email_address

    - prompt: _(Web Address)
      type: text
      name: web_address
      attrs:
        - key: placeholder
          value: 'http://'

    - prompt: _(Number of Employees)
      type: number
      name: num_of_employee

    - prompt: _(Opening Date)
      type: month
      name: opening_date
      attrs:
        key: placeholder
        value: 'YYYY-MM'

    - prompt: _(Owner Place of Residence)
      type: textarea
      name: owner_residence

    - label: _(Owner identifies as...)
      type: fieldset
      name: owner_identity
      items:
        - type: toggle
          label: _(Caucasian)
          name: owner_is_caucasian
        - type: toggle
          label: _(African American)
          name: owner_is_african_american
        - type: toggle
          label: _(Hispanic)
          name: owner_is_hispanic
        - type: toggle
          label: _(Asian)
          name: owner_is_asian
        - type: toggle
          label: _(Veteran)
          name: owner_is_veteran
        - type: toggle
          label: _(Female)
          name: owner_is_female

    - prompt: _(Are there any issues with this listing?)
      type: switch
      name: problems

    - prompt: ""
      type: textarea
      name: problem_description
      attrs:
        - key: placeholder
          value: _(Note issues with the listing here.)
      condition:
        - field: problems
          value: checked

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

#pages:
#  - title: _(About)
#    slug: about
#    name: overview
#    start_page: true

#  - title: _(Why Shareabouts?)
#    slug: why
#    url: /static/pages/why.html

#  - title: _(Features)
#    slug: features
#    url: /static/pages/features.html

#  - title: _(Feedback)
#    external: true
#    url: https://openplans.zendesk.com/anonymous_requests/new
