# Settings for the app
app:
  # HTML Title
  title: OurMiami
  # Header name
  name: OurMiami
  # Meta description that will show up in Google search results
  meta_description: _('The Miami Foundation and our partners created the Our Miami Public Space Challenge to discover the best ideas for improving, creating, and activating local public spaces.')

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: fasle
  options:
    center:
      lat: 25.79571825588276
      lng: -80.24002075195312
    zoom: 12
    minZoom: 10
    maxZoom: 18
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-jo9bww2s/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  ChildIdea:
    default: puck-green
    focused: red
    label: _(Child or Senior Citizen Focused Idea)
  CommunityGatheringSpace:
    default: puck-blue
    focused: red
    label: _(Community Gathering Space)
  ExistingPlaceMakeover:
    default: puck-yellow
    focused: red
    label: _(Existing Place Makeover)
  GardenFarmersMarket:
    default: puck-red
    focused: red
    label: _(Garden/Farmer's Market/Healthy Eating)    
  NightFocusedIdea:
    default: puck-purple
    focused: red
    label: _(Night Focused Idea)
  ParkParkletPlaza:
    default: puck-blue
    focused: red
    label: _(Park/Parklet/Plaza)
  PublicWaterfront:
    default: puck-yellow
    focused: red
    label: _(Public Waterfront)
  SafeStreets:
    default: puck-red
    focused: red
    label: _(Safe Streets)    
  ShadePublicComfort:
    default: puck-purple
    focused: red
    label: _(Shade and Public Comfort)
  PhysicalActivity:
    default: puck-green
    focused: red
    label: _(Physical Activity/Exercise)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  puck-green:
    iconUrl: /static/css/images/markers/dot-70d52c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-blue:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-yellow:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-red:
    iconUrl: /static/css/images/markers/dot-e1264d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-purple:
    iconUrl: /static/css/images/markers/dot-744edc.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add an idea)
  action_text: _(suggested)
  title: _(Tell us more...)
  action_text: _(suggested)
  anonymous_name: _(Someone)
  submit_button_label: _(Post it to the map)
  items:
    - prompt: _(My idea to improve this place... (required))
      type: textarea
      name: description
      optional: false
      label: _(My idea to improve this place...)
      attrs:
        - key: placeholder
          value: _(...short term, low cost, block focused, all street scale or smaller ideas welcome...)
        - key: required
          value: required
    - prompt: _(So that people could... (required))
      type: textarea
      name: details
      optional: false
      label: _(So that people could...)
      attrs:
        - key: placeholder
          value: _(Tell us why this idea would help make our Miami better)
        - key: required
          value: required
    - prompt: _(Idea type (Required))
      label: _(Idea type)
      type: select
      options:
        - label: _(please choose)
          value: ""
        - label: _(Child or Senior Citizen Focused Idea)
          value: ChildIdea
        - label: _(Community Gathering Space)
          value: CommunityGatheringSpace
        - label: _(Existing Place Makeover)
          value: ExistingPlaceMakeover
        - label: _(Garden/Farmer's Market/Healthy Eating)
          value: GardenFarmersMarket
        - label: _(Night Focused Idea)
          value: NightFocusedIdea
        - label: _(Park/Parklet/Plaza)
          value: ParkParkletPlaza
        - label: _(Physical Activity/Exercise)
          value: PhysicalActivity
        - label: _(Public Waterfront)
          value: PublicWaterfront
        - label: _(Safe Streets)
          value: SafeStreets
        - label: _(Shade and Public Comfort)
          value: ShadePublicComfort
      attrs:
      - key: required
        value: required         
      name: location_type
    - prompt: _(Your Name)
      label: _(Suggested by)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Your or your organization's name will get credit for your idea publically)
        - key: size
          value: 30
    - prompt: _(Your email (required))
      type: email
      optional: false
      name: private-email
      attrs:
        - key: placeholder
          value: _(Your email will not be shown publicly)
        - key: size
          value: 30
        - key: required
          value: required
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Add a link)
      type: text
      name: infolink
      attrs:
        - key: placeholder
          value: _(Add a link to page related to your idea, e.g. more info about it, or an example)
        - key: size
          value: 30
    - type: hidden
      name: private-conf
      attrs:
        - key: value
          value: "Not sent"

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Like This!)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
  - title: _(Contact us)
    slug: contact
    name: features
  - title: _(Filter)
    sub_pages:
      - title: All
        external: true
        url: /
      - title: SafeStreets
        external: true
        url: /SafeStreets